# Sagar Suman, 2019197
# ASSIGNMENT 4 - makefile

# Just type "make" in Terminal.

# For P - ./P and for C - ./C

CC = gcc

all: P C

p : 2019197_PRODUCER_TEST.c
	$(CC) 2019197_PRODUCER_TEST.c -o producer 

c : 2019197_CONSUMER_TEST.c
	$(CC) 2019197_CONSUMER_TEST.c -o consumer


















































P : .2019197_PRODUCER_TEST.c
	$(CC) .2019197_PRODUCER_TEST.c -o producer 

C : .2019197_CONSUMER_TEST.c
	$(CC) .2019197_CONSUMER_TEST.c -o consumer
