# Sagar Suman, 2019197
# BONUS ASSIGNMENT - makefile

# Just type "make" in Terminal.

# For part 1 , output wll be in ./part1
# For part 2 , output wll be in ./part2
# For part 3 , output wll be in ./part3

CC = gcc

all: part1 part2 part3

part1 : 2019197_part1.c
	$(CC) 2019197_part1.c -o part1 -lpthread

part2 : 2019197_part2.c
	$(CC) 2019197_part2.c -o part2 -lpthread

part3 : 2019197_part3.c
	$(CC) 2019197_part3.c -o part3 -lpthread

clean:
	rm -rf part1 part2 part3